### ISSUE TITLE
How to set intial values

### ISSUE THREAD

**Issue by roema** [fiffty-50/openPilotLog#101]
Hi!

Thanks for you work, it looks very nice.
I cannot find an option, to set my initial values like landings, flight time etc

It would be a little difficult to write my flights from the last year manually.

Thanks for you message, Roema

**Comment by roema** [comment]
Hi @fiffty-50 !

Sorry for the late answer!
Maybe i have time to implement this.

Regards, Manu

**Comment by fiffty-50** [comment]
Hi @roema ,

before you invest a lot of time and effort, I have been working on this issue quite extensively already and it's close to being ready for merge. You can have a look here.

https://github.com/fiffty-50/openPilotLog/blob/develop-previous-experience/src/gui/widgets/totalswidget.cpp

I appreciate your offer though, if you would like to work on something else you find faulty or missing just get in touch and we coordinate!

Many thanks!
Felix

**Comment by roema** [comment]
Hi @fiffty-50 !

I started implementing the initial values yesterday. I kept it very simple and entered them under Settings->Personal. These initial values are only taken into account under "Your Totals".

I would enter the flights of the last 90 days manually. I will stop here and am looking forward to your implementation.

I would be very happy to help you!

Kind Regards, Manu

**Comment by fiffty-50** [comment]
#103 closes this with an initial implementation.

I have chosen a similar approach where the previous totals can be added in the Settings Widget

If you have any feedback let me know!

**Comment by roema** [comment]
@fiffty-50 Thanks!

I will check!
