### ISSUE TITLE
Default Style Sheet Dark

### ISSUE THREAD

**Issue by fiffty-50** [fiffty-50/openpilotlog#53]
Observed behaviour:

On first run, the FirstRunDialog is styled with the dark stylesheet

Desired behaviour:

Default stylesheet should be no style shee.

Observed on: Windows 10, Qt 5.15.2

Steps to reproduce: Delete all config files and start the application.

Additional Observation: Fusion is a good choice for windows, the 'native' windows style looks horrible.

**Comment by KotzaBoss** [comment]
Confirm commit 82dda30e515223a794b5145ace3b7c21f509a277 works as requested
