### ISSUE TITLE
openPilotLog not compatible with QStringBuilder globally

### ISSUE THREAD

**Issue by fiffty-50** [fiffty-50/openpilotlog#56]
Qt offers [QStringBuilder](https://doc.qt.io/qt-5/qstring.html#more-efficient-string-construction) to efficiently create strings from concatenations using the `%` operator to replace `+`.

If `DEFINES *= QT_USE_QSTRINGBUILDER` is in the .pro file, the `+` operator can be used in the source code and will automatically interpreted as `%` where appropriate, making its use very convenient. Unfortunately this solution is not entirely source compatible, and currently not possible for this project.

Using the `%` operator is counter-intuitive and not a widely known way of concatenating strings, so it would be desirable to be able to enable QStringBuilder globally and keep using the `+` operator.

In order to enable QStringBuilder globally, we would need to refactor the incompatible code. At a first view these seem to be the parts creating problems:

- REPR makro
- ADatabaseError

**Comment by KotzaBoss** [comment]
How are they creating problems?

**Comment by KotzaBoss** [comment]
For ADatabaseError any assignment should be explicitely ADatabaseError. `operator=` seems to have trouble with QStringBuilder
```c++
if (errorCount == 0) {
        query.prepare(QStringLiteral("COMMIT"));
        query.exec();
        if(query.lastError().type() == QSqlError::NoError) {
            emit dataBaseUpdated();
            lastError = ADatabaseError();
            return true;
        } else {
            lastError = ADatabaseError("Transaction unsuccessful (Interrupted). Error count: " + QString::number(errorCount));
            return false;
        }
    } else {
        query.prepare(QStringLiteral("ROLLBACK"));
        query.exec();
        lastError = ADatabaseError("Transaction unsuccessful (no changes have been made). Error count: " + QString::number(errorCount));
        return false;
    }
```
If + is going to be global then any concatenation must be explicitely QString. It seems that implicit conversions dont occur.
```c++
 REPR(DataPosition,
         "tableName=" + object.tableName + ", "
         "rowId=" + QString::number(object.rowId)
         )
```
